language: node_js

node_js:
  - "7"

script:
  yarn test
  yarn build
  yarn deploy

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  on:
    branch: master
